apiVersion: xl-release/v1
kind: Templates
spec:
  - type: xlrelease.ThemeSettings
    id: Configuration/settings/ThemeSettings
    headerName: LLM integration (SDK)
    headerAccentColor: ORANGE
    description: Instance for testing the LLM integration plugin
    loginMessage: |-
      Welcome to the Digital.ai Release SDK Environment!
      Use this server to test the LLM integration plugin
